<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class AddSoinsInfirmiersServices extends Seeder
{
    public function run(): void
    {
        // Get the Soins Infirmiers type service ID
        $soinsInfirmiersType = \App\Models\TypeService::where('NomType', 'Soins Infirmiers')->first();
        
        if (!$soinsInfirmiersType) {
            // If type service doesn't exist, create it first (fallback)
            $soinsInfirmiersType = \App\Models\TypeService::create([
                'NomType' => 'Soins Infirmiers',
                'description' => 'Services de soins infirmiers généraux et spécialisés',
                'status' => 1,
                'IDgen_mst_Departement' => 1, // Médecine Interne
            ]);
        }

        $services = [
            // Soins Infirmiers Courants
            [
                'id_gen_mst_service' => 'SI001',
                'n_ordre' => 1,
                'short_name' => 'Injection Simple',
                'tri_name' => 'INJECTION SIMPLE',
                'code_local' => 'SI001',
                'cle_tarif_service' => 'TARIF_SI001',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 2000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI001',
                'code_hl7' => 'SI001',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI002',
                'n_ordre' => 2,
                'short_name' => 'Injection Complexe',
                'tri_name' => 'INJECTION COMPLEXE',
                'code_local' => 'SI002',
                'cle_tarif_service' => 'TARIF_SI002',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 3500,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI002',
                'code_hl7' => 'SI002',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI003',
                'n_ordre' => 3,
                'short_name' => 'Prélèvement Sanguin',
                'tri_name' => 'PRELEVEMENT SANGUIN',
                'code_local' => 'SI003',
                'cle_tarif_service' => 'TARIF_SI003',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 2000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI003',
                'code_hl7' => 'SI003',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI004',
                'n_ordre' => 4,
                'short_name' => 'Forfait Perfusion',
                'tri_name' => 'FORFAIT PERFUSION',
                'code_local' => 'SI004',
                'cle_tarif_service' => 'TARIF_SI004',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 5000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI004',
                'code_hl7' => 'SI004',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            
            // Soins de Plaies
            [
                'id_gen_mst_service' => 'SI005',
                'n_ordre' => 5,
                'short_name' => 'Pansement Simple',
                'tri_name' => 'PANSEMENT SIMPLE',
                'code_local' => 'SI005',
                'cle_tarif_service' => 'TARIF_SI005',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 2500,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI005',
                'code_hl7' => 'SI005',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI006',
                'n_ordre' => 6,
                'short_name' => 'Pansement Lourd',
                'tri_name' => 'PANSEMENT LOURD',
                'code_local' => 'SI006',
                'cle_tarif_service' => 'TARIF_SI006',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 8000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI006',
                'code_hl7' => 'SI006',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI007',
                'n_ordre' => 7,
                'short_name' => 'Ablation de Matériel',
                'tri_name' => 'ABLATION MATERIEL',
                'code_local' => 'SI007',
                'cle_tarif_service' => 'TARIF_SI007',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 3000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI007',
                'code_hl7' => 'SI007',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            
            // Petite Chirurgie
            [
                'id_gen_mst_service' => 'SI008',
                'n_ordre' => 8,
                'short_name' => 'Suture Simple',
                'tri_name' => 'SUTURE SIMPLE',
                'code_local' => 'SI008',
                'cle_tarif_service' => 'TARIF_SI008',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 15000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI008',
                'code_hl7' => 'SI008',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI009',
                'n_ordre' => 9,
                'short_name' => 'Suture Profonde',
                'tri_name' => 'SUTURE PROFONDE',
                'code_local' => 'SI009',
                'cle_tarif_service' => 'TARIF_SI009',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 25000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI009',
                'code_hl7' => 'SI009',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI010',
                'n_ordre' => 10,
                'short_name' => 'Traitement d\'Abcès',
                'tri_name' => 'TRAITEMENT ABCES',
                'code_local' => 'SI010',
                'cle_tarif_service' => 'TARIF_SI010',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 20000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI010',
                'code_hl7' => 'SI010',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI011',
                'n_ordre' => 11,
                'short_name' => 'Exérèse de Kyste',
                'tri_name' => 'EXERESIS KISTE',
                'code_local' => 'SI011',
                'cle_tarif_service' => 'TARIF_SI011',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 30000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI011',
                'code_hl7' => 'SI011',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI012',
                'n_ordre' => 12,
                'short_name' => 'Circoncision',
                'tri_name' => 'CIRCONCISION',
                'code_local' => 'SI012',
                'cle_tarif_service' => 'TARIF_SI012',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 400000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI012',
                'code_hl7' => 'SI012',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            
            // Examens Techniques
            [
                'id_gen_mst_service' => 'SI013',
                'n_ordre' => 13,
                'short_name' => 'Pose DIU',
                'tri_name' => 'POSE DIU',
                'code_local' => 'SI013',
                'cle_tarif_service' => 'TARIF_SI013',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 15000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI013',
                'code_hl7' => 'SI013',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI014',
                'n_ordre' => 14,
                'short_name' => 'Frottis Cervico-Vaginal',
                'tri_name' => 'FROTTIS CERVICO-VAGINAL',
                'code_local' => 'SI014',
                'cle_tarif_service' => 'TARIF_SI014',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 7500,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI014',
                'code_hl7' => 'SI014',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI015',
                'n_ordre' => 15,
                'short_name' => 'Échographie Pelvienne',
                'tri_name' => 'ECHOGRAPHIE PELVIENNE',
                'code_local' => 'SI015',
                'cle_tarif_service' => 'TARIF_SI015',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 15000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI015',
                'code_hl7' => 'SI015',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI016',
                'n_ordre' => 16,
                'short_name' => 'Écho Datation de Grossesse',
                'tri_name' => 'ECHO DATATION GROSSESSE',
                'code_local' => 'SI016',
                'cle_tarif_service' => 'TARIF_SI016',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 10000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI016',
                'code_hl7' => 'SI016',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI017',
                'n_ordre' => 17,
                'short_name' => 'Écho Morphologie Fœtale',
                'tri_name' => 'ECHO MORPHOLOGIE FOETALE',
                'code_local' => 'SI017',
                'cle_tarif_service' => 'TARIF_SI017',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 25000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI017',
                'code_hl7' => 'SI017',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI018',
                'n_ordre' => 18,
                'short_name' => 'ECG de Repos',
                'tri_name' => 'ECG REPOS',
                'code_local' => 'SI018',
                'cle_tarif_service' => 'TARIF_SI018',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 12000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI018',
                'code_hl7' => 'SI018',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI019',
                'n_ordre' => 19,
                'short_name' => 'Aérosol / Nébulisation',
                'tri_name' => 'AEROSOL NEBULISATION',
                'code_local' => 'SI019',
                'cle_tarif_service' => 'TARIF_SI019',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 5000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI019',
                'code_hl7' => 'SI019',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            
            // Biologie de Base
            [
                'id_gen_mst_service' => 'SI020',
                'n_ordre' => 20,
                'short_name' => 'Bilan Standard',
                'tri_name' => 'BILAN STANDARD',
                'code_local' => 'SI020',
                'cle_tarif_service' => 'TARIF_SI020',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 20000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI020',
                'code_hl7' => 'SI020',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI021',
                'n_ordre' => 21,
                'short_name' => 'Test de Grossesse (HCG)',
                'tri_name' => 'TEST GROSSESSE HCG',
                'code_local' => 'SI021',
                'cle_tarif_service' => 'TARIF_SI021',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 5000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI021',
                'code_hl7' => 'SI021',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
            [
                'id_gen_mst_service' => 'SI022',
                'n_ordre' => 22,
                'short_name' => 'ECBU',
                'tri_name' => 'ECBU',
                'code_local' => 'SI022',
                'cle_tarif_service' => 'TARIF_SI022',
                'groupe_id' => 1,
                'categorie_id' => 1,
                'type_categorie' => 'Soins Infirmiers',
                'status' => 1,
                'valeur_cts' => 10000,
                'majoration_ferie' => 0,
                'code_snomed' => 'SI022',
                'code_hl7' => 'SI022',
                'IDgen_mst_Type_Service' => $soinsInfirmiersType->IDgen_mst_Type_Service,
            ],
        ];

        foreach ($services as $serviceData) {
            Service::updateOrCreate(
                ['id_gen_mst_service' => $serviceData['id_gen_mst_service']],
                $serviceData
            );
        }
    }
}