<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ProductItemSeeder extends Seeder
{
    public function run(): void
    {
        $exists = DB::table('ph_mst_item')->count();
        if ($exists > 0) {
            return;
        }

        $produits = [
            [
                'item_id' => 'MED001',
                'description' => 'Paracétamol 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 5,
                'duration' => 5,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'midi' => '12h00',
                'soir' => '20h00',
                'dddadulte' => 4,
                'max_prise' => 4,
                'prixcAchat' => 1500,
                'PrixVente' => 2500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED002',
                'description' => 'Amoxicilline 1g',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 7,
                'duration' => 7,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 0,
                'subustitution' => 1,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 3200,
                'PrixVente' => 4500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED003',
                'description' => 'Ibuprofène 400mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 3,
                'duration' => 3,
                'duration_type' => 'jour',
                'food_type' => 'apres',
                'renew' => 0,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'midi' => '12h00',
                'soir' => '20h00',
                'dddadulte' => 3,
                'max_prise' => 3,
                'prixcAchat' => 2500,
                'PrixVente' => 3500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED004',
                'description' => 'Métrodinidazole 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 7,
                'duration' => 7,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 2800,
                'PrixVente' => 3800,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED005',
                'description' => 'Aspirine 100mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'apres',
                'renew' => 1,
                'subustitution' => 0,
                'for_all_prescription' => 1,
                'couche' => 'Au coucher',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 1200,
                'PrixVente' => 2000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED006',
                'description' => 'Ciprofloxacine 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 5,
                'duration' => 5,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 4500,
                'PrixVente' => 6000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED007',
                'description' => 'Oméprazole 20mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 gélule',
                'days' => 14,
                'duration' => 14,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 1,
                'subustitution' => 0,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 3500,
                'PrixVente' => 5000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED008',
                'description' => 'Azithromycine 250mg',
                'voie_administration' => 'Orale',
                'posologie' => '2 gélules',
                'days' => 3,
                'duration' => 3,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'dddadulte' => 2,
                'max_prise' => 1,
                'prixcAchat' => 5500,
                'PrixVente' => 7500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED009',
                'description' => 'Metformine 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 2200,
                'PrixVente' => 3000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED010',
                'description' => 'Amlodipine 5mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'couche' => 'Au coucher',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 2800,
                'PrixVente' => 4000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED011',
                'description' => 'Captopril 25mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 1800,
                'PrixVente' => 2500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED012',
                'description' => 'Hydrochlorothiazide 25mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'matin',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 1500,
                'PrixVente' => 2000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED013',
                'description' => 'Atorvastatine 20mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'soir',
                'renew' => 1,
                'subustitution' => 0,
                'for_all_prescription' => 1,
                'soir' => '20h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 4200,
                'PrixVente' => 5500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED014',
                'description' => 'Levofloxacine 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 7,
                'duration' => 7,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 6500,
                'PrixVente' => 8500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED015',
                'description' => 'Céfuroxime 250mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 5,
                'duration' => 5,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 3800,
                'PrixVente' => 5200,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED016',
                'description' => 'Prednisolone 20mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 5,
                'duration' => 5,
                'duration_type' => 'jour',
                'food_type' => 'matin',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 2500,
                'PrixVente' => 3500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED017',
                'description' => 'Sertraline 50mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'soir',
                'renew' => 1,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'soir' => '20h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 5500,
                'PrixVente' => 7500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED018',
                'description' => 'Fluconazole 150mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 gélule',
                'days' => 1,
                'duration' => 1,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 1200,
                'PrixVente' => 1800,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED019',
                'description' => 'Albendazole 400mg',
                'voie_administration' => 'Orale',
                'posologie' => '2 comprimés',
                'days' => 1,
                'duration' => 1,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 800,
                'PrixVente' => 1200,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED020',
                'description' => 'Ventoline 100mcg',
                'voie_administration' => 'Inhalation',
                'posologie' => '2 bouffées',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 1,
                'subustitution' => 0,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'soir' => '20h00',
                'max_prise' => 4,
                'prixcAchat' => 1800,
                'PrixVente' => 2500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED021',
                'description' => 'Diclofenac 50mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 7,
                'duration' => 7,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 0,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'midi' => '12h00',
                'soir' => '20h00',
                'dddadulte' => 3,
                'max_prise' => 3,
                'prixcAchat' => 1600,
                'PrixVente' => 2200,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED022',
                'description' => 'Loratadine 10mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 10,
                'duration' => 10,
                'duration_type' => 'jour',
                'food_type' => 'indifferent',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 1200,
                'PrixVente' => 1800,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED023',
                'description' => 'Ranitidine 150mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 14,
                'duration' => 14,
                'duration_type' => 'jour',
                'food_type' => 'avant',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 1400,
                'PrixVente' => 2000,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED024',
                'description' => 'Clarithromycine 500mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 7,
                'duration' => 7,
                'duration_type' => 'jour',
                'food_type' => 'pendant',
                'renew' => 0,
                'subustitution' => 0,
                'for_all_prescription' => 0,
                'matin' => '8h00',
                'soir' => '20h00',
                'dddadulte' => 2,
                'max_prise' => 2,
                'prixcAchat' => 4800,
                'PrixVente' => 6500,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
            [
                'item_id' => 'MED025',
                'description' => 'Furosémide 40mg',
                'voie_administration' => 'Orale',
                'posologie' => '1 comprimé',
                'days' => 30,
                'duration' => 30,
                'duration_type' => 'jour',
                'food_type' => 'matin',
                'renew' => 1,
                'subustitution' => 1,
                'for_all_prescription' => 1,
                'matin' => '8h00',
                'dddadulte' => 1,
                'max_prise' => 1,
                'prixcAchat' => 900,
                'PrixVente' => 1300,
                'status_id' => 1,
                'created_user_id' => 'SYSTEM',
                'created_dttm' => now(),
            ],
        ];

        foreach ($produits as $p) {
            DB::table('ph_mst_item')->insert($p);
        }
    }
}